CREATE OR REPLACE VIEW ADV_SBX.TBLS._SRM_RCS____WEEKLY_RELCAND_1_P_ADJ AS
WITH PB AS (
    SELECT 
        P.*, 
        B.CMTSFQDNDESC, 
        B.MARKET, 
        B.REGION
    FROM
        TBLS._SRM_RCS____WEEKLY_RELCAND_1_P P
    JOIN 
        TBLS.SRM_MODEL_DATA B
    ON 
        P._KEY = B._KEY
    WHERE 
        B.CALDT_K >= ADD_MONTHS(DATEADD(MONTH, -1, CURRENT_DATE), -5)
)
SELECT 
    _KEY, 
    PB.CALDT, 
    Y, 
    P, 
    P_UNADJUSTED, 
    SCORE_SK,
    CMTS_CF.CF AS P_ADJ_CMTS,
    MARKET_CF.CF AS P_ADJ_MARKET,
    REGION_CF.CF AS P_ADJ_REGION
FROM
    PB
LEFT JOIN (
    SELECT 
        CALDT, 
        CMTSFQDNDESC, 
        COUNT(*) AS CNT, 
        AVG(Y) AS AVG_Y, 
        AVG(P) AS AVG_P, 
        AVG(Y) / AVG(P) AS CF
    FROM 
        PB
    GROUP BY 
        CALDT, CMTSFQDNDESC
) CMTS_CF 
ON 
    PB.CMTSFQDNDESC = CMTS_CF.CMTSFQDNDESC 
    AND PB.CALDT = CMTS_CF.CALDT
LEFT JOIN (
    SELECT 
        CALDT, 
        MARKET, 
        COUNT(*) AS CNT, 
        AVG(Y) AS AVG_Y, 
        AVG(P) AS AVG_P, 
        AVG(Y) / AVG(P) AS CF
    FROM 
        PB
    GROUP BY 
        CALDT, MARKET
) MARKET_CF 
ON 
    PB.MARKET = MARKET_CF.MARKET 
    AND PB.CALDT = MARKET_CF.CALDT
LEFT JOIN (
    SELECT 
        CALDT, 
        REGION, 
        COUNT(*) AS CNT, 
        AVG(Y) AS AVG_Y, 
        AVG(P) AS AVG_P, 
        AVG(Y) / AVG(P) AS CF
    FROM 
        PB
    GROUP BY 
        CALDT, REGION
) REGION_CF 
ON 
    PB.REGION = REGION_CF.REGION 
    AND PB.CALDT = REGION_CF.CALDT;
