create or replace view dlbiadvdanltcs._SRM_RCS____WEEKLY_RELCAND_1_P_ADJ AS
WITH PB AS  (
SELECT  P._KEY, P.CALDT, CAST(P.Y AS FLOAT), CAST(P.P AS FLOAT), P.p_unadjusted, P.SCORE_SK , B.CMTSFQDNDESC, B.MARKET, B.REGION 
FROM 
	dlbiadvdanltcs._SRM_RCS____WEEKLY_RELCAND_1_P P
	JOIN dlbiadvdanltcs.SRM_MODEL_DATA  B 
		ON P._KEY = B._KEY 
    WHERE CALDT_K >= ADD_MONTHS(CURRENT_DATE() - 1,-5)
)
SELECT _KEY, PB.CALDT, Y, P, p_unadjusted, SCORE_SK
	, P*CMTS_CF.CF AS P_ADJ_CMTS
	, P*MARKET_CF.CF AS P_ADJ_MARKET
	, P*REGION_CF.CF AS P_ADJ_REGION 
FROM 
	PB
	LEFT JOIN 
	(
		SELECT CALDT, CMTSFQDNDESC, COUNT(*), AVG(Y), AVG(P), AVG(Y) / AVG(P) AS CF 
		FROM PB 
		GROUP BY 1, 2  
	) CMTS_CF ON EQUAL_NULL (PB.CMTSFQDNDESC  ,  CMTS_CF.CMTSFQDNDESC) AND PB.CALDT = CMTS_CF.CALDT 
	LEFT JOIN 
	(
		SELECT CALDT, MARKET , COUNT(*), AVG(Y), AVG(P), AVG(Y) / AVG(P) AS CF 
		FROM PB 
		GROUP BY 1, 2  
	) MARKET_CF ON EQUAL_NULL (PB.MARKET  ,   MARKET_CF.MARKET ) AND PB.CALDT = MARKET_CF.CALDT 
	LEFT JOIN 
	(
		SELECT CALDT, REGION  , COUNT(*), AVG(Y), AVG(P), AVG(Y) / AVG(P) AS CF 
		FROM PB 
		GROUP BY 1, 2  
	) REGION_CF  ON EQUAL_NULL (PB.REGION  ,  REGION_CF.REGION ) AND PB.CALDT = REGION_CF.CALDT;
